import { chromium } from 'playwright';
import path from 'node:path';
const url = 'file://' + path.resolve('proof/docs.html');
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: {width:1440,height:900} });
const pg = await ctx.newPage();
const errs = [];
pg.on('console', m => { if(m.type()==='error') errs.push(m.text()); });
pg.on('pageerror', e => errs.push('PAGEERROR: '+e.message));
await pg.goto(url, { waitUntil:'load' });
await pg.waitForTimeout(300);
const md = await pg.evaluate(() => window.PAGE_MD || (typeof PAGE_MD!=='undefined'?PAGE_MD:null));
console.log('PAGE_MD length:', md ? md.length : 'undefined');
console.log('contains old stale 4,7,9,11,12:', md ? md.includes('4,7,9,11,12') : 'n/a');
console.log('contains new 4,6,9,11,13:', md ? md.includes('[4,6,9,11,13]') : 'n/a');
console.log('contains Agent view section:', md ? md.includes('## 6. The Agent view') : 'n/a');
console.log('contains Since 1995 section:', md ? md.includes('## 7. "Since 1995"') : 'n/a');
console.log('contains verify-print section:', md ? md.includes('verify-print.mjs') : 'n/a');
console.log('errors:', JSON.stringify(errs));
await ctx.close(); await b.close();
